title: New York Metro Papyrology Workshop
year: 2025
email: dr128@nyu.edu
description: Website for the 2025 New York Metro Papyrology workshop at ISAW NYU
baseurl: "/isaw_metropap25"
url: "https://isaw.github.io"
github_username: dmratzan

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
